views:
  - name: content_search_classification
    description: "Migrated from content_search_classified_results.lkml"

    cubes:
      - join_path: content_search_classified_results
        includes: "*"
        excludes:
          - id
          - version_id
          - etl_created_at
          - active_days
          