DROP TABLE import.adjust_campaign_performance;


CREATE TABLE import.adjust_campaign_performance (
    day DATE encode zstd,
    network VARCHAR ENCODE ZSTD,
    campaign VARCHAR ENCODE ZSTD,
    adgroup VARCHAR ENCODE ZSTD,
    country_code VARCHAR ENCODE ZSTD,
    creative VARCHAR ENCODE ZSTD,
    os_name VARCHAR ENCODE ZSTD,
    clicks integer ENCODE az64,
    impressions integer ENCODE az64,
    installs integer ENCODE az64,
    limit_ad_tracking_installs integer ENCODE az64,
    limit_ad_tracking_install_rate double precision ENCODE zstd,
    sessions integer ENCODE az64,
    cost double precision ENCODE zstd,
    revenue double precision ENCODE zstd,
    gdpr_forgets integer ENCODE az64,
    age_above_44_events integer ENCODE az64,
    age_below_30_events integer ENCODE az64,
    age_between_30_and_44_events integer ENCODE az64,
    did_create_account_events integer ENCODE az64,
    paid_clue_plus_12m_events integer ENCODE az64,
    paid_clue_plus_1m_events integer ENCODE az64,
    renewed_clue_plus_12m_events integer ENCODE az64,
    renewed_clue_plus_1m_events integer ENCODE az64,
    start_free_trial_clue_plus_events integer ENCODE az64,
    paid_clue_plus_12m_d0_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_12m_d0_conversions_cohort integer ENCODE az64,
    paid_clue_plus_1m_d0_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_1m_d0_conversions_cohort integer ENCODE az64,
    start_free_trial_clue_plus_d0_revenue_cohort double precision ENCODE zstd,
    start_free_trial_clue_plus_d0_conversions_cohort integer ENCODE az64,
    paid_clue_plus_12m_w0_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_12m_w0_conversions_cohort integer ENCODE az64,
    paid_clue_plus_1m_w0_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_1m_w0_conversions_cohort integer ENCODE az64,
    start_free_trial_clue_plus_w0_revenue_cohort double precision ENCODE zstd,
    start_free_trial_clue_plus_w0_conversions_cohort integer ENCODE az64,
    paid_clue_plus_12m_m0_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_12m_m0_conversions_cohort integer ENCODE az64,
    paid_clue_plus_1m_m0_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_1m_m0_conversions_cohort integer ENCODE az64,
    start_free_trial_clue_plus_m0_revenue_cohort double precision ENCODE zstd,
    start_free_trial_clue_plus_m0_conversions_cohort integer ENCODE az64,
    paid_clue_plus_12m_m1_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_12m_m1_conversions_cohort integer ENCODE az64,
    paid_clue_plus_1m_m1_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_1m_m1_conversions_cohort integer ENCODE az64,
    start_free_trial_clue_plus_m1_revenue_cohort double precision ENCODE zstd,
    start_free_trial_clue_plus_m1_conversions_cohort integer ENCODE az64,
    paid_clue_plus_12m_m2_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_12m_m2_conversions_cohort integer ENCODE az64,
    paid_clue_plus_1m_m2_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_1m_m2_conversions_cohort integer ENCODE az64,
    start_free_trial_clue_plus_m2_revenue_cohort double precision ENCODE zstd,
    start_free_trial_clue_plus_m2_conversions_cohort integer ENCODE az64, 
    paid_clue_plus_12m_m3_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_12m_m3_conversions_cohort integer ENCODE az64,
    paid_clue_plus_1m_m3_revenue_cohort double precision ENCODE zstd,
    paid_clue_plus_1m_m3_conversions_cohort integer ENCODE az64,
    start_free_trial_clue_plus_m3_revenue_cohort double precision ENCODE zstd,
    start_free_trial_clue_plus_m3_conversions_cohort integer ENCODE az64,
    skad_installs integer ENCODE az64,
    conversion_1 integer ENCODE az64,
    conversion_2 integer ENCODE az64,
    conversion_3 integer ENCODE az64,
    conversion_4 integer ENCODE az64,
    conversion_5 integer ENCODE az64,
    conversion_6 integer ENCODE az64,
    etl_timestamp TIMESTAMP WITH TIME ZONE ENCODE ZSTD
);