-- -- rolls up raw adjust report and then joins it to the backend conversions report (intermediate.backend_campaign_performance)
-- CREATE TABLE IF NOT EXISTS temp.intermediate_adjust_campaign_performance (
--     date date,
--     network string,
--     campaign string,
--     campaign_name string,
--     campaign_id string,
--     adgroup string,
--     adgroup_name string,
--     adgroup_id string,
--     country_code string,
--     country string,
--     creative string,
--     creative_name string,
--     creative_id string,
--     platform string,
--     clicks int,
--     impressions int,
--     installs int,
--     limit_ad_tracking_installs int,
--     limit_ad_tracking_install_rate double,
--     sessions int,
--     cost double,
--     revenue double,
--     gdpr_forgets int,
--     age_above_44_events int,
--     age_below_30_events int,
--     age_between_30_and_44_events int,
--     d0_created_account_conversions int,
--     d0_free_trial_conversions int,
--     d0_1m_subscription_conversions int,
--     d0_1m_subscription_revenue double,
--     d0_12m_subscription_conversions int,
--     d0_12m_subscription_revenue double,
--     d7_created_account_conversions int,
--     d7_free_trial_conversions int,
--     d7_1m_subscription_conversions int,
--     d7_1m_subscription_revenue double,
--     d7_12m_subscription_conversions int,
--     d7_12m_subscription_revenue double,
--     d30_created_account_conversions int,
--     d30_free_trial_conversions int,
--     d30_1m_subscription_conversions int,
--     d30_1m_subscription_revenue double,
--     d30_12m_subscription_conversions int,
--     d30_12m_subscription_revenue double,
--     d120_created_account_conversions int,
--     d120_free_trial_conversions int,
--     d120_1m_subscription_conversions int,
--     d120_1m_subscription_revenue double,
--     d120_12m_subscription_conversions int,
--     d120_12m_subscription_revenue double,
--     skad_installs int,
--     skad_event_1_conversions int,
--     skad_event_2_conversions int,
--     skad_event_3_conversions int,
--     skad_event_4_conversions int,
--     skad_event_5_conversions int,
--     skad_event_6_conversions int,
--     skad_reinstalls double,
--     network_ad_spend_skan double,
--     skad_coarse_conversion_values_null_0 double,
--     skad_coarse_conversion_values_none_0 double,
--     skad_coarse_conversion_values_low_0 double,
--     skad_coarse_conversion_values_medium_0 double,
--     skad_coarse_conversion_values_high_0 double,
--     skad_coarse_conversion_values_null_1 double,
--     skad_coarse_conversion_values_none_1 double,
--     skad_coarse_conversion_values_low_1 double,
--     skad_coarse_conversion_values_medium_1 double,
--     skad_coarse_conversion_values_high_1 double,
--     skad_coarse_conversion_values_null_2 double,
--     skad_coarse_conversion_values_none_2 double,
--     skad_coarse_conversion_values_low_2 double,
--     skad_coarse_conversion_values_medium_2 double,
--     skad_coarse_conversion_values_high_2 double,
--     etl_timestamp date,
--     d0_backend_created_account_conversions int,
--     d0_backend_free_trial_conversions int,
--     d0_backend_1m_subscription_conversions int,
--     d0_backend_1m_subscription_revenue double,
--     d0_backend_12m_subscription_conversions int,
--     d0_backend_12m_subscription_revenue double,
--     d0_backend_partner_subscription_conversions int,
--     d0_backend_partner_subscription_revenue double,
--     d7_backend_created_account_conversions int,
--     d7_backend_free_trial_conversions int,
--     d7_backend_1m_subscription_conversions int,
--     d7_backend_1m_subscription_revenue double,
--     d7_backend_12m_subscription_conversions int,
--     d7_backend_12m_promo_subscription_conversions int,
--     d7_backend_12m_subscription_revenue double,
--     d7_backend_partner_subscription_conversions int,
--     d7_backend_partner_subscription_revenue double,
--     d30_backend_created_account_conversions int,
--     d30_backend_free_trial_conversions int,
--     d30_backend_1m_subscription_conversions int,
--     d30_backend_1m_subscription_revenue double,
--     d30_backend_12m_subscription_conversions int,
--     d30_backend_12m_subscription_revenue double,
--     d30_backend_partner_subscription_conversions int,
--     d30_backend_partner_subscription_revenue double,
--     d120_backend_created_account_conversions int,
--     d120_backend_free_trial_conversions int,
--     d120_backend_1m_subscription_conversions int,
--     d120_backend_1m_subscription_revenue double,
--     d120_backend_12m_subscription_conversions int,
--     d120_backend_12m_subscription_revenue double,
--     d120_backend_partner_subscription_conversions int,
--     d120_backend_partner_subscription_revenue double,
--     d360_backend_created_account_conversions int,
--     d360_backend_free_trial_conversions int,
--     d360_backend_1m_subscription_conversions int,
--     d360_backend_1m_subscription_revenue double,
--     d360_backend_12m_subscription_conversions int,
--     d360_backend_12m_subscription_revenue double,
--     d360_backend_partner_subscription_conversions int,
--     d360_backend_partner_subscription_revenue double
--     )
--     LOCATION 's3://clue-data-prod-athena-iceberg-storage/iceberg/temp/intermediate_adjust_campaign_performance'
--     TBLPROPERTIES (
--     'table_type'='iceberg'
-- );

-- DELETE FROM temp.intermediate_adjust_campaign_performance;

INSERT INTO temp.intermediate_adjust_campaign_performance (
    date,
    network,
    campaign,
    campaign_name,
    campaign_id,
    adgroup,
    adgroup_name,
    adgroup_id,
    country_code,
    country,
    creative,
    creative_name,
    creative_id,
    platform,
    clicks,
    impressions,
    installs,
    limit_ad_tracking_installs,
    limit_ad_tracking_install_rate,
    sessions,
    cost,
    revenue,
    gdpr_forgets,
    age_above_44_events,
    age_below_30_events,
    age_between_30_and_44_events,
    d0_created_account_conversions,
    d0_free_trial_conversions,
    d0_1m_subscription_conversions,
    d0_1m_subscription_revenue,
    d0_12m_subscription_conversions,
    d0_12m_subscription_revenue,
    d7_created_account_conversions,
    d7_free_trial_conversions,
    d7_1m_subscription_conversions,
    d7_1m_subscription_revenue,
    d7_12m_subscription_conversions,
    d7_12m_subscription_revenue,
    d30_created_account_conversions,
    d30_free_trial_conversions,
    d30_1m_subscription_conversions,
    d30_1m_subscription_revenue,
    d30_12m_subscription_conversions,
    d30_12m_subscription_revenue,
    d120_created_account_conversions,
    d120_free_trial_conversions,
    d120_1m_subscription_conversions,
    d120_1m_subscription_revenue,
    d120_12m_subscription_conversions,
    d120_12m_subscription_revenue,
    skad_installs,
    skad_event_1_conversions,
    skad_event_2_conversions,
    skad_event_3_conversions,
    skad_event_4_conversions,
    skad_event_5_conversions,
    skad_event_6_conversions,
    skad_reinstalls,
    network_ad_spend_skan,
    skad_coarse_conversion_values_null_0,
    skad_coarse_conversion_values_none_0,
    skad_coarse_conversion_values_low_0,
    skad_coarse_conversion_values_medium_0,
    skad_coarse_conversion_values_high_0,
    skad_coarse_conversion_values_null_1,
    skad_coarse_conversion_values_none_1,
    skad_coarse_conversion_values_low_1,
    skad_coarse_conversion_values_medium_1,
    skad_coarse_conversion_values_high_1,
    skad_coarse_conversion_values_null_2,
    skad_coarse_conversion_values_none_2,
    skad_coarse_conversion_values_low_2,
    skad_coarse_conversion_values_medium_2,
    skad_coarse_conversion_values_high_2,
    etl_timestamp,
    d0_backend_created_account_conversions,
    d0_backend_free_trial_conversions,
    d0_backend_1m_subscription_conversions,
    d0_backend_1m_subscription_revenue,
    d0_backend_12m_subscription_conversions,
    d0_backend_12m_subscription_revenue,
    d0_backend_partner_subscription_conversions,
    d0_backend_partner_subscription_revenue,
    d7_backend_created_account_conversions,
    d7_backend_free_trial_conversions,
    d7_backend_1m_subscription_conversions,
    d7_backend_1m_subscription_revenue,
    d7_backend_12m_subscription_conversions,
    d7_backend_12m_promo_subscription_conversions,
    d7_backend_12m_subscription_revenue,
    d7_backend_partner_subscription_conversions,
    d7_backend_partner_subscription_revenue,
    d30_backend_created_account_conversions,
    d30_backend_free_trial_conversions,
    d30_backend_1m_subscription_conversions,
    d30_backend_1m_subscription_revenue,
    d30_backend_12m_subscription_conversions,
    d30_backend_12m_subscription_revenue,
    d30_backend_partner_subscription_conversions,
    d30_backend_partner_subscription_revenue,
    d120_backend_created_account_conversions,
    d120_backend_free_trial_conversions,
    d120_backend_1m_subscription_conversions,
    d120_backend_1m_subscription_revenue,
    d120_backend_12m_subscription_conversions,
    d120_backend_12m_subscription_revenue,
    d120_backend_partner_subscription_conversions,
    d120_backend_partner_subscription_revenue,
    d360_backend_created_account_conversions,
    d360_backend_free_trial_conversions,
    d360_backend_1m_subscription_conversions,
    d360_backend_1m_subscription_revenue,
    d360_backend_12m_subscription_conversions,
    d360_backend_12m_subscription_revenue,
    d360_backend_partner_subscription_conversions,
    d360_backend_partner_subscription_revenue
)
WITH adjust AS (
    SELECT
        day AS date,
        network,
        CASE WHEN campaign = 'unknown (1809913192032305)' THEN 'English_TikTok_Installs_iOS_ZA&1809913192032305' ELSE campaign END AS campaign,
        COALESCE(TRIM(campaign_network),
                 CASE WHEN campaign = 'unknown (1809913192032305)' THEN 'English_TikTok_Installs_iOS_ZA&1809913192032305'
                      ELSE NULLIF(TRIM(REGEXP_REPLACE(campaign, '\s*\(\d+\)$', '')), '') END
                 ,'unknown') AS campaign_name,
        NULLIF(COALESCE(NULLIF(TRIM(REGEXP_REPLACE(campaign_id_network,'[^0-9]','')),''), NULLIF(REGEXP_EXTRACT(campaign, '\((\d+)\)$', 1),'')), 'unknown') AS campaign_id,
        adgroup,
        COALESCE(TRIM(adgroup_network), NULLIF(TRIM(REGEXP_REPLACE(adgroup, '\s*\(\d+\)$', '')), ''),'unknown') AS adgroup_name,
        NULLIF(COALESCE(NULLIF(REGEXP_REPLACE(adgroup_id_network,'[^0-9]',''),''), NULLIF(REGEXP_EXTRACT(adgroup, '\((\d+)\)$', 1),'')), 'unknown') AS adgroup_id,
        creative,
        COALESCE(TRIM(creative_network), NULLIF(TRIM(REGEXP_REPLACE(creative, '\s*\(\d+\)$', '')), ''),'unknown') AS creative_name,
        NULLIF(COALESCE(NULLIF(REGEXP_REPLACE(creative_id_network,'[^0-9]',''),''), NULLIF(REGEXP_EXTRACT(creative, '\((\d+)\)$', 1),'')), 'unknown') AS creative_id,
        UPPER(country_code) AS country_code,
        country_name AS country,
        os_name AS platform,
        etl_timestamp,
        SUM(CASE WHEN network like 'Google Ads%' OR network like '%Facebook%' OR network like '%Instagram%' OR network = 'Apple Search Ads' OR network like 'Tiktok%'
                 THEN network_clicks
                 ELSE clicks END) AS clicks,
        SUM(CASE WHEN network like 'Google Ads%' OR network like '%Facebook%' OR network like '%Instagram%' OR network = 'Apple Search Ads'  OR network like 'Tiktok%'
                 THEN network_impressions
                 ELSE impressions END) AS impressions,
        SUM(installs) AS installs,
        SUM(limit_ad_tracking_installs) AS limit_ad_tracking_installs,
        MAX(limit_ad_tracking_install_rate) AS limit_ad_tracking_install_rate,
        SUM(sessions) AS sessions,
        SUM(cost) AS cost,
        SUM(revenue) AS revenue,
        SUM(gdpr_forgets) AS gdpr_forgets,
        SUM(age_above_44_events) AS age_above_44_events,
        SUM(age_below_30_events) AS age_below_30_events,
        SUM(age_between_30_and_44_events) AS age_between_30_and_44_events,

        -- d0 metrics
        SUM(did_create_account_d0_conversions_cohort) as d0_created_account_conversions,
        SUM(start_free_trial_clue_plus_d0_conversions_cohort) AS d0_free_trial_conversions,
        SUM(paid_clue_plus_1m_d0_conversions_cohort) AS d0_1m_subscription_conversions,
        SUM(paid_clue_plus_1m_d0_revenue_cohort) AS d0_1m_subscription_revenue,
        SUM(paid_clue_plus_12m_d0_conversions_cohort) AS d0_12m_subscription_conversions,
        SUM(paid_clue_plus_12m_d0_revenue_cohort) AS d0_12m_subscription_revenue,

        -- d7 metrics
        SUM(did_create_account_d7_conversions_cohort) as d7_created_account_conversions,
        SUM(start_free_trial_clue_plus_d7_conversions_cohort) AS d7_free_trial_conversions,
        SUM(paid_clue_plus_1m_d7_conversions_cohort) AS d7_1m_subscription_conversions,
        SUM(paid_clue_plus_1m_d7_revenue_cohort) AS d7_1m_subscription_revenue,
        SUM(paid_clue_plus_12m_d7_conversions_cohort) AS d7_12m_subscription_conversions,
        SUM(paid_clue_plus_12m_d7_revenue_cohort) AS d7_12m_subscription_revenue,

        -- d30 metrics
        SUM(did_create_account_d30_conversions_cohort) as d30_created_account_conversions,
        SUM(start_free_trial_clue_plus_d30_conversions_cohort) AS d30_free_trial_conversions,
        SUM(paid_clue_plus_1m_d30_conversions_cohort) AS d30_1m_subscription_conversions,
        SUM(paid_clue_plus_1m_d30_revenue_cohort) AS d30_1m_subscription_revenue,
        SUM(paid_clue_plus_12m_d30_conversions_cohort) AS d30_12m_subscription_conversions,
        SUM(paid_clue_plus_12m_d30_revenue_cohort) AS d30_12m_subscription_revenue,

        -- d120 metrics
        SUM(did_create_account_d120_conversions_cohort) as d120_created_account_conversions,
        SUM(start_free_trial_clue_plus_d120_conversions_cohort) AS d120_free_trial_conversions,
        SUM(paid_clue_plus_1m_d120_conversions_cohort) AS d120_1m_subscription_conversions,
        SUM(paid_clue_plus_1m_d120_revenue_cohort) AS d120_1m_subscription_revenue,
        SUM(paid_clue_plus_12m_d120_conversions_cohort) AS d120_12m_subscription_conversions,
        SUM(paid_clue_plus_12m_d120_revenue_cohort) AS d120_12m_subscription_revenue,

        -- skadnetwork metrics
        SUM(skad_installs) AS skad_installs,
        SUM(conversion_1) AS skad_event_1_conversions,
        SUM(conversion_2) AS skad_event_2_conversions,
        SUM(conversion_3) AS skad_event_3_conversions,
        SUM(conversion_4) AS skad_event_4_conversions,
        SUM(conversion_5) AS skad_event_5_conversions,
        SUM(conversion_6) AS skad_event_6_conversions,
        SUM(skad_reinstalls) AS skad_reinstalls,
        SUM(network_ad_spend_skan) AS network_ad_spend_skan,
        SUM(skad_coarse_conversion_values_null_0) AS skad_coarse_conversion_values_null_0,
        SUM(skad_coarse_conversion_values_none_0) AS skad_coarse_conversion_values_none_0,
        SUM(skad_coarse_conversion_values_low_0) AS skad_coarse_conversion_values_low_0,
        SUM(skad_coarse_conversion_values_medium_0) AS skad_coarse_conversion_values_medium_0,
        SUM(skad_coarse_conversion_values_high_0) AS skad_coarse_conversion_values_high_0,
        SUM(skad_coarse_conversion_values_null_1) AS skad_coarse_conversion_values_null_1,
        SUM(skad_coarse_conversion_values_none_1) AS skad_coarse_conversion_values_none_1,
        SUM(skad_coarse_conversion_values_low_1) AS skad_coarse_conversion_values_low_1,
        SUM(skad_coarse_conversion_values_medium_1) AS skad_coarse_conversion_values_medium_1,
        SUM(skad_coarse_conversion_values_high_1) AS skad_coarse_conversion_values_high_1,
        SUM(skad_coarse_conversion_values_null_2) AS skad_coarse_conversion_values_null_2,
        SUM(skad_coarse_conversion_values_none_2) AS skad_coarse_conversion_values_none_2,
        SUM(skad_coarse_conversion_values_low_2) AS skad_coarse_conversion_values_low_2,
        SUM(skad_coarse_conversion_values_medium_2) AS skad_coarse_conversion_values_medium_2,
        SUM(skad_coarse_conversion_values_high_2) AS skad_coarse_conversion_values_high_2

    FROM import.adjust_campaign_performance
    LEFT JOIN core.countries
        ON UPPER(country_code) = iso_alpha_2
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
),

standard AS (
SELECT
    adjust.date,
    adjust.network,
    adjust.campaign,
    adjust.campaign_name,
    adjust.campaign_id,
    adjust.adgroup,
    adjust.adgroup_name,
    adjust.adgroup_id,
    adjust.country_code,
    adjust.country,
    adjust.creative,
    adjust.creative_name,
    adjust.creative_id,
    adjust.platform,
    adjust.clicks,
    adjust.impressions,
    adjust.installs,
    adjust.limit_ad_tracking_installs,
    adjust.limit_ad_tracking_install_rate,
    adjust.sessions,
    adjust.cost,
    adjust.revenue,
    adjust.gdpr_forgets,
    adjust.age_above_44_events,
    adjust.age_below_30_events,
    adjust.age_between_30_and_44_events,
    adjust.d0_created_account_conversions,
    adjust.d0_free_trial_conversions,
    adjust.d0_1m_subscription_conversions,
    adjust.d0_1m_subscription_revenue,
    adjust.d0_12m_subscription_conversions,
    adjust.d0_12m_subscription_revenue,
    adjust.d7_created_account_conversions,
    adjust.d7_free_trial_conversions,
    adjust.d7_1m_subscription_conversions,
    adjust.d7_1m_subscription_revenue,
    adjust.d7_12m_subscription_conversions,
    adjust.d7_12m_subscription_revenue,
    adjust.d30_created_account_conversions,
    adjust.d30_free_trial_conversions,
    adjust.d30_1m_subscription_conversions,
    adjust.d30_1m_subscription_revenue,
    adjust.d30_12m_subscription_conversions,
    adjust.d30_12m_subscription_revenue,
    adjust.d120_created_account_conversions,
    adjust.d120_free_trial_conversions,
    adjust.d120_1m_subscription_conversions,
    adjust.d120_1m_subscription_revenue,
    adjust.d120_12m_subscription_conversions,
    adjust.d120_12m_subscription_revenue,
    adjust.skad_installs,
    adjust.skad_event_1_conversions,
    adjust.skad_event_2_conversions,
    adjust.skad_event_3_conversions,
    adjust.skad_event_4_conversions,
    adjust.skad_event_5_conversions,
    adjust.skad_event_6_conversions,
    adjust.skad_reinstalls,
    adjust.network_ad_spend_skan,
    adjust.skad_coarse_conversion_values_null_0,
    adjust.skad_coarse_conversion_values_none_0,
    adjust.skad_coarse_conversion_values_low_0,
    adjust.skad_coarse_conversion_values_medium_0,
    adjust.skad_coarse_conversion_values_high_0,
    adjust.skad_coarse_conversion_values_null_1,
    adjust.skad_coarse_conversion_values_none_1,
    adjust.skad_coarse_conversion_values_low_1,
    adjust.skad_coarse_conversion_values_medium_1,
    adjust.skad_coarse_conversion_values_high_1,
    adjust.skad_coarse_conversion_values_null_2,
    adjust.skad_coarse_conversion_values_none_2,
    adjust.skad_coarse_conversion_values_low_2,
    adjust.skad_coarse_conversion_values_medium_2,
    adjust.skad_coarse_conversion_values_high_2,
    adjust.etl_timestamp,
    COALESCE(backend_campaign_performance.d0_created_account_conversions,0) AS d0_backend_created_account_conversions,
    COALESCE(backend_campaign_performance.d0_free_trial_conversions,0) AS d0_backend_free_trial_conversions,
    COALESCE(backend_campaign_performance.d0_1m_subscription_conversions,0) AS d0_backend_1m_subscription_conversions,
    COALESCE(backend_campaign_performance.d0_1m_subscription_revenue,0) AS d0_backend_1m_subscription_revenue,
    COALESCE(backend_campaign_performance.d0_12m_subscription_conversions,0) AS d0_backend_12m_subscription_conversions,
    COALESCE(backend_campaign_performance.d0_12m_subscription_revenue,0) AS d0_backend_12m_subscription_revenue,
    COALESCE(backend_campaign_performance.d0_partner_subscription_conversions,0) AS d0_backend_partner_subscription_conversions,
    COALESCE(backend_campaign_performance.d0_partner_subscription_revenue,0) AS d0_backend_partner_subscription_revenue,

    COALESCE(backend_campaign_performance.d7_created_account_conversions,0) AS d7_backend_created_account_conversions,
    COALESCE(backend_campaign_performance.d7_free_trial_conversions,0) AS d7_backend_free_trial_conversions,
    COALESCE(backend_campaign_performance.d7_1m_subscription_conversions,0) AS d7_backend_1m_subscription_conversions,
    COALESCE(backend_campaign_performance.d7_1m_subscription_revenue,0) AS d7_backend_1m_subscription_revenue,
    COALESCE(backend_campaign_performance.d7_12m_subscription_conversions,0) AS d7_backend_12m_subscription_conversions,
    COALESCE(backend_campaign_performance.d7_12m_promo_subscription_conversions,0) AS d7_backend_12m_promo_subscription_conversions,
    COALESCE(backend_campaign_performance.d7_12m_subscription_revenue,0) AS d7_backend_12m_subscription_revenue,
    COALESCE(backend_campaign_performance.d7_partner_subscription_conversions,0) AS d7_backend_partner_subscription_conversions,
    COALESCE(backend_campaign_performance.d7_partner_subscription_revenue,0) AS d7_backend_partner_subscription_revenue,

    COALESCE(backend_campaign_performance.d30_created_account_conversions,0) AS d30_backend_created_account_conversions,
    COALESCE(backend_campaign_performance.d30_free_trial_conversions,0) AS d30_backend_free_trial_conversions,
    COALESCE(backend_campaign_performance.d30_1m_subscription_conversions,0) AS d30_backend_1m_subscription_conversions,
    COALESCE(backend_campaign_performance.d30_1m_subscription_revenue,0) AS d30_backend_1m_subscription_revenue,
    COALESCE(backend_campaign_performance.d30_12m_subscription_conversions,0) AS d30_backend_12m_subscription_conversions,
    COALESCE(backend_campaign_performance.d30_12m_subscription_revenue,0) AS d30_backend_12m_subscription_revenue,
    COALESCE(backend_campaign_performance.d30_partner_subscription_conversions,0) AS d30_backend_partner_subscription_conversions,
    COALESCE(backend_campaign_performance.d30_partner_subscription_revenue,0) AS d30_backend_partner_subscription_revenue,

    COALESCE(backend_campaign_performance.d120_created_account_conversions,0) AS d120_backend_created_account_conversions,
    COALESCE(backend_campaign_performance.d120_free_trial_conversions,0) AS d120_backend_free_trial_conversions,
    COALESCE(backend_campaign_performance.d120_1m_subscription_conversions,0) AS d120_backend_1m_subscription_conversions,
    COALESCE(backend_campaign_performance.d120_1m_subscription_revenue,0) AS d120_backend_1m_subscription_revenue,
    COALESCE(backend_campaign_performance.d120_12m_subscription_conversions,0) AS d120_backend_12m_subscription_conversions,
    COALESCE(backend_campaign_performance.d120_12m_subscription_revenue,0) AS d120_backend_12m_subscription_revenue,
    COALESCE(backend_campaign_performance.d120_partner_subscription_conversions,0) AS d120_backend_partner_subscription_conversions,
    COALESCE(backend_campaign_performance.d120_partner_subscription_revenue,0) AS d120_backend_partner_subscription_revenue,

    COALESCE(backend_campaign_performance.d360_created_account_conversions,0) AS d360_backend_created_account_conversions,
    COALESCE(backend_campaign_performance.d360_free_trial_conversions,0) AS d360_backend_free_trial_conversions,
    COALESCE(backend_campaign_performance.d360_1m_subscription_conversions,0) AS d360_backend_1m_subscription_conversions,
    COALESCE(backend_campaign_performance.d360_1m_subscription_revenue,0) AS d360_backend_1m_subscription_revenue,
    COALESCE(backend_campaign_performance.d360_12m_subscription_conversions,0) AS d360_backend_12m_subscription_conversions,
    COALESCE(backend_campaign_performance.d360_12m_subscription_revenue,0) AS d360_backend_12m_subscription_revenue,
    COALESCE(backend_campaign_performance.d360_partner_subscription_conversions,0) AS d360_backend_partner_subscription_conversions,
    COALESCE(backend_campaign_performance.d360_partner_subscription_revenue,0) AS d360_backend_partner_subscription_revenue

FROM adjust
LEFT JOIN temp.intermediate_backend_campaign_performance AS backend_campaign_performance
    ON (adjust.date = backend_campaign_performance.date
        AND adjust.network = backend_campaign_performance.network
        AND COALESCE(adjust.campaign_id, adjust.campaign_name, adjust.campaign) = COALESCE(backend_campaign_performance.campaign_id, backend_campaign_performance.campaign_name, backend_campaign_performance.campaign)
        AND COALESCE(adjust.adgroup_id, adjust.adgroup_name, adjust.adgroup) = COALESCE(backend_campaign_performance.adgroup_id, backend_campaign_performance.adgroup_name, backend_campaign_performance.adgroup)
        AND adjust.country_code = backend_campaign_performance.country_code
        AND adjust.country = backend_campaign_performance.country
        AND COALESCE(adjust.creative_id, adjust.creative_name, adjust.creative) = COALESCE(backend_campaign_performance.creative_id, backend_campaign_performance.creative_name, backend_campaign_performance.creative)
        AND adjust.platform = backend_campaign_performance.platform)
WHERE adjust.network NOT LIKE 'TikTok%'
),

-- there's some duplication of tiktok creative ids across different creative names. therefore we have to rollup this network by creative id before joining
tiktok_rollup AS (
    SELECT
        date,
        network,
        campaign,
        campaign_name,
        campaign_id,
        adgroup,
        adgroup_name,
        adgroup_id,
        country_code,
        country,
        COALESCE(creative_id, creative_name, creative) as creative_id_coalesce_creative,
        platform,
        SUM(d0_created_account_conversions) AS d0_created_account_conversions,
        SUM(d0_free_trial_conversions) AS d0_free_trial_conversions,
        SUM(d0_1m_subscription_conversions) AS d0_1m_subscription_conversions,
        SUM(d0_1m_subscription_revenue) AS d0_1m_subscription_revenue,
        SUM(d0_12m_subscription_conversions) AS d0_12m_subscription_conversions,
        SUM(d0_12m_subscription_revenue) AS d0_12m_subscription_revenue,
        SUM(d0_partner_subscription_conversions) AS d0_partner_subscription_conversions,
        SUM(d0_partner_subscription_revenue) AS d0_partner_subscription_revenue,

        SUM(d7_created_account_conversions) AS d7_created_account_conversions,
        SUM(d7_free_trial_conversions) AS d7_free_trial_conversions,
        SUM(d7_1m_subscription_conversions) AS d7_1m_subscription_conversions,
        SUM(d7_1m_subscription_revenue) AS d7_1m_subscription_revenue,
        SUM(d7_12m_subscription_conversions) AS d7_12m_subscription_conversions,
        SUM(d7_12m_promo_subscription_conversions) as d7_12m_promo_subscription_conversions,
        SUM(d7_12m_subscription_revenue) AS d7_12m_subscription_revenue,
        SUM(d7_partner_subscription_conversions) AS d7_partner_subscription_conversions,
        SUM(d7_partner_subscription_revenue) AS d7_partner_subscription_revenue,

        SUM(d30_created_account_conversions) AS d30_created_account_conversions,
        SUM(d30_free_trial_conversions) AS d30_free_trial_conversions,
        SUM(d30_1m_subscription_conversions) AS d30_1m_subscription_conversions,
        SUM(d30_1m_subscription_revenue) AS d30_1m_subscription_revenue,
        SUM(d30_12m_subscription_conversions) AS d30_12m_subscription_conversions,
        SUM(d30_12m_subscription_revenue) AS d30_12m_subscription_revenue,
        SUM(d30_partner_subscription_conversions) AS d30_partner_subscription_conversions,
        SUM(d30_partner_subscription_revenue) AS d30_partner_subscription_revenue,

        SUM(d120_created_account_conversions) AS d120_created_account_conversions,
        SUM(d120_free_trial_conversions) AS d120_free_trial_conversions,
        SUM(d120_1m_subscription_conversions) AS d120_1m_subscription_conversions,
        SUM(d120_1m_subscription_revenue) AS d120_1m_subscription_revenue,
        SUM(d120_12m_subscription_conversions) AS d120_12m_subscription_conversions,
        SUM(d120_12m_subscription_revenue) AS d120_12m_subscription_revenue,
        SUM(d120_partner_subscription_conversions) AS d120_partner_subscription_conversions,
        SUM(d120_partner_subscription_revenue) AS d120_partner_subscription_revenue,

        SUM(d360_created_account_conversions) AS d360_created_account_conversions,
        SUM(d360_free_trial_conversions) AS d360_free_trial_conversions,
        SUM(d360_1m_subscription_conversions) AS d360_1m_subscription_conversions,
        SUM(d360_1m_subscription_revenue) AS d360_1m_subscription_revenue,
        SUM(d360_12m_subscription_conversions) AS d360_12m_subscription_conversions,
        SUM(d360_12m_subscription_revenue) AS d360_12m_subscription_revenue,
        SUM(d360_partner_subscription_conversions) AS d360_partner_subscription_conversions,
        SUM(d360_partner_subscription_revenue) AS d360_partner_subscription_revenue

    FROM temp.intermediate_backend_campaign_performance
    WHERE network like 'TikTok%' and NOT tiktok_san_tracker_name
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
),

tiktok AS (
SELECT
    adjust.date,
    adjust.network,
    adjust.campaign,
    adjust.campaign_name,
    adjust.campaign_id,
    adjust.adgroup,
    adjust.adgroup_name,
    adjust.adgroup_id,
    adjust.country_code,
    adjust.country,
    adjust.creative,
    adjust.creative_name,
    adjust.creative_id,
    adjust.platform,
    adjust.clicks,
    adjust.impressions,
    adjust.installs,
    adjust.limit_ad_tracking_installs,
    adjust.limit_ad_tracking_install_rate,
    adjust.sessions,
    adjust.cost,
    adjust.revenue,
    adjust.gdpr_forgets,
    adjust.age_above_44_events,
    adjust.age_below_30_events,
    adjust.age_between_30_and_44_events,
    adjust.d0_created_account_conversions,
    adjust.d0_free_trial_conversions,
    adjust.d0_1m_subscription_conversions,
    adjust.d0_1m_subscription_revenue,
    adjust.d0_12m_subscription_conversions,
    adjust.d0_12m_subscription_revenue,
    adjust.d7_created_account_conversions,
    adjust.d7_free_trial_conversions,
    adjust.d7_1m_subscription_conversions,
    adjust.d7_1m_subscription_revenue,
    adjust.d7_12m_subscription_conversions,
    adjust.d7_12m_subscription_revenue,
    adjust.d30_created_account_conversions,
    adjust.d30_free_trial_conversions,
    adjust.d30_1m_subscription_conversions,
    adjust.d30_1m_subscription_revenue,
    adjust.d30_12m_subscription_conversions,
    adjust.d30_12m_subscription_revenue,
    adjust.d120_created_account_conversions,
    adjust.d120_free_trial_conversions,
    adjust.d120_1m_subscription_conversions,
    adjust.d120_1m_subscription_revenue,
    adjust.d120_12m_subscription_conversions,
    adjust.d120_12m_subscription_revenue,
    adjust.skad_installs,
    adjust.skad_event_1_conversions,
    adjust.skad_event_2_conversions,
    adjust.skad_event_3_conversions,
    adjust.skad_event_4_conversions,
    adjust.skad_event_5_conversions,
    adjust.skad_event_6_conversions,
    adjust.skad_reinstalls,
    adjust.network_ad_spend_skan,
    adjust.skad_coarse_conversion_values_null_0,
    adjust.skad_coarse_conversion_values_none_0,
    adjust.skad_coarse_conversion_values_low_0,
    adjust.skad_coarse_conversion_values_medium_0,
    adjust.skad_coarse_conversion_values_high_0,
    adjust.skad_coarse_conversion_values_null_1,
    adjust.skad_coarse_conversion_values_none_1,
    adjust.skad_coarse_conversion_values_low_1,
    adjust.skad_coarse_conversion_values_medium_1,
    adjust.skad_coarse_conversion_values_high_1,
    adjust.skad_coarse_conversion_values_null_2,
    adjust.skad_coarse_conversion_values_none_2,
    adjust.skad_coarse_conversion_values_low_2,
    adjust.skad_coarse_conversion_values_medium_2,
    adjust.skad_coarse_conversion_values_high_2,
    adjust.etl_timestamp,
    COALESCE(tiktok_rollup.d0_created_account_conversions,0) AS d0_backend_created_account_conversions,
    COALESCE(tiktok_rollup.d0_free_trial_conversions,0) AS d0_backend_free_trial_conversions,
    COALESCE(tiktok_rollup.d0_1m_subscription_conversions,0) AS d0_backend_1m_subscription_conversions,
    COALESCE(tiktok_rollup.d0_1m_subscription_revenue,0) AS d0_backend_1m_subscription_revenue,
    COALESCE(tiktok_rollup.d0_12m_subscription_conversions,0) AS d0_backend_12m_subscription_conversions,
    COALESCE(tiktok_rollup.d0_12m_subscription_revenue,0) AS d0_backend_12m_subscription_revenue,
    COALESCE(tiktok_rollup.d0_partner_subscription_conversions,0) AS d0_backend_partner_subscription_conversions,
    COALESCE(tiktok_rollup.d0_partner_subscription_revenue,0) AS d0_backend_partner_subscription_revenue,

    COALESCE(tiktok_rollup.d7_created_account_conversions,0) AS d7_backend_created_account_conversions,
    COALESCE(tiktok_rollup.d7_free_trial_conversions,0) AS d7_backend_free_trial_conversions,
    COALESCE(tiktok_rollup.d7_1m_subscription_conversions,0) AS d7_backend_1m_subscription_conversions,
    COALESCE(tiktok_rollup.d7_1m_subscription_revenue,0) AS d7_backend_1m_subscription_revenue,
    COALESCE(tiktok_rollup.d7_12m_subscription_conversions,0) AS d7_backend_12m_subscription_conversions,
    COALESCE(tiktok_rollup.d7_12m_promo_subscription_conversions,0) AS d7_backend_12m_promo_subscription_conversions,
    COALESCE(tiktok_rollup.d7_12m_subscription_revenue,0) AS d7_backend_12m_subscription_revenue,
    COALESCE(tiktok_rollup.d7_partner_subscription_conversions,0) AS d7_backend_partner_subscription_conversions,
    COALESCE(tiktok_rollup.d7_partner_subscription_revenue,0) AS d7_backend_partner_subscription_revenue,

    COALESCE(tiktok_rollup.d30_created_account_conversions,0) AS d30_backend_created_account_conversions,
    COALESCE(tiktok_rollup.d30_free_trial_conversions,0) AS d30_backend_free_trial_conversions,
    COALESCE(tiktok_rollup.d30_1m_subscription_conversions,0) AS d30_backend_1m_subscription_conversions,
    COALESCE(tiktok_rollup.d30_1m_subscription_revenue,0) AS d30_backend_1m_subscription_revenue,
    COALESCE(tiktok_rollup.d30_12m_subscription_conversions,0) AS d30_backend_12m_subscription_conversions,
    COALESCE(tiktok_rollup.d30_12m_subscription_revenue,0) AS d30_backend_12m_subscription_revenue,
    COALESCE(tiktok_rollup.d30_partner_subscription_conversions,0) AS d30_backend_partner_subscription_conversions,
    COALESCE(tiktok_rollup.d30_partner_subscription_revenue,0) AS d30_backend_partner_subscription_revenue,

    COALESCE(tiktok_rollup.d120_created_account_conversions,0) AS d120_backend_created_account_conversions,
    COALESCE(tiktok_rollup.d120_free_trial_conversions,0) AS d120_backend_free_trial_conversions,
    COALESCE(tiktok_rollup.d120_1m_subscription_conversions,0) AS d120_backend_1m_subscription_conversions,
    COALESCE(tiktok_rollup.d120_1m_subscription_revenue,0) AS d120_backend_1m_subscription_revenue,
    COALESCE(tiktok_rollup.d120_12m_subscription_conversions,0) AS d120_backend_12m_subscription_conversions,
    COALESCE(tiktok_rollup.d120_12m_subscription_revenue,0) AS d120_backend_12m_subscription_revenue,
    COALESCE(tiktok_rollup.d120_partner_subscription_conversions,0) AS d120_backend_partner_subscription_conversions,
    COALESCE(tiktok_rollup.d120_partner_subscription_revenue,0) AS d120_backend_partner_subscription_revenue,

    COALESCE(tiktok_rollup.d360_created_account_conversions,0) AS d360_backend_created_account_conversions,
    COALESCE(tiktok_rollup.d360_free_trial_conversions,0) AS d360_backend_free_trial_conversions,
    COALESCE(tiktok_rollup.d360_1m_subscription_conversions,0) AS d360_backend_1m_subscription_conversions,
    COALESCE(tiktok_rollup.d360_1m_subscription_revenue,0) AS d360_backend_1m_subscription_revenue,
    COALESCE(tiktok_rollup.d360_12m_subscription_conversions,0) AS d360_backend_12m_subscription_conversions,
    COALESCE(tiktok_rollup.d360_12m_subscription_revenue,0) AS d360_backend_12m_subscription_revenue,
    COALESCE(tiktok_rollup.d360_partner_subscription_conversions,0) AS d360_backend_partner_subscription_conversions,
    COALESCE(tiktok_rollup.d360_partner_subscription_revenue,0) AS d360_backend_partner_subscription_revenue

FROM adjust
LEFT JOIN tiktok_rollup
    ON (adjust.date = tiktok_rollup.date
        and adjust.network = tiktok_rollup.network
        and COALESCE(adjust.campaign_id, adjust.campaign_name, adjust.campaign) = COALESCE(tiktok_rollup.campaign_id, tiktok_rollup.campaign_name, tiktok_rollup.campaign)
        and COALESCE(adjust.adgroup_id, adjust.adgroup_name, adjust.adgroup) = COALESCE(tiktok_rollup.adgroup_id, tiktok_rollup.adgroup_name, tiktok_rollup.adgroup)
        and adjust.country_code = tiktok_rollup.country_code
        and adjust.country = tiktok_rollup.country
        and COALESCE(adjust.creative_id, adjust.creative_name, adjust.creative) = tiktok_rollup.creative_id_coalesce_creative
        and adjust.platform = tiktok_rollup.platform)
WHERE adjust.network LIKE 'TikTok%'
)

SELECT * FROM tiktok
UNION ALL
SELECT * FROM standard
;