-- CREATE TABLE science.pms_cc_user_sample (
--     user_id string,
--     analytics_id string,
--     first_start_date date
-- )
-- LOCATION 's3://clue-data-prod-athena-iceberg-storage/iceberg/science/pms_cc_user_sample'
-- TBLPROPERTIES (
--   'table_type'='iceberg'
-- );

-- INSERT INTO science.pms_cc_user_sample (
--     user_id,
--     analytics_id,
--     first_start_date
-- )
-- SELECT user_id, backend_mode_switchers.analytics_id, MIN(start_date) AS first_start_date
-- FROM der.backend_mode_switchers
-- JOIN import.users ON (backend_mode_switchers.analytics_id = users.analytics_id)
-- WHERE mode = 'CONCEIVE'
-- AND start_date BETWEEN DATE '2023-08-01' AND DATE '2024-08-01'
-- GROUP BY 1, 2
-- ;

---------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------

-- CREATE TABLE science.cc_user_cycle_logs (
--     id string,
--     user_id string,
--     analytics_id string,
--     first_entered_cc_mode date,
--     mode string,
--     tracking_event_revision bigint,
--     created_at timestamp,
--     cycle_excluded boolean,
--     cycle_start date,
--     cycle_end date,
--     is_predicted boolean,
--     period string,
--     conception string,
--     ovulation string,
--     pms string,
--     fertile string,
--     levels string,
--     current_cycle boolean
-- )
-- LOCATION 's3://clue-data-prod-athena-iceberg-storage/iceberg/science/cc_user_cycle_logs'
-- TBLPROPERTIES (
--   'table_type'='iceberg'
-- );

-- CREATE TABLE science.cc_user_predicted_cycles (
--     id string,
--     user_id string,
--     analytics_id string,
--     first_entered_cc_mode date,
--     mode string,
--     tracking_event_revision bigint,
--     created_at timestamp,
--     cycle_excluded boolean,
--     cycle_start date,
--     cycle_end date,
--     is_predicted boolean,
--     period string,
--     conception string,
--     ovulation string,
--     pms string,
--     fertile string,
--     levels string,
--     current_cycle boolean
-- )
-- LOCATION 's3://clue-data-prod-athena-iceberg-storage/iceberg/science/cc_user_predicted_cycles'
-- TBLPROPERTIES (
--   'table_type'='iceberg'
-- );

-- CREATE TABLE science.cc_user_cycles (
--     id string,
--     user_id string,
--     analytics_id string,
--     first_entered_cc_mode date,
--     mode string,
--     tracking_event_revision bigint,
--     created_at timestamp,
--     cycle_excluded boolean,
--     cycle_start date,
--     cycle_end date,
--     is_predicted boolean,
--     period string,
--     conception string,
--     ovulation string,
--     pms string,
--     fertile string,
--     levels string,
--     current_cycle boolean
-- )
-- LOCATION 's3://clue-data-prod-athena-iceberg-storage/iceberg/science/cc_user_cycles'
-- TBLPROPERTIES (
--   'table_type'='iceberg'
-- );

---------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------
