-- CREATE TABLE temp.new_user_activation_metrics_v1 AS (
-- WITH new_users AS (
--     SELECT
--         analytics_id,
--         account_created_at,
--         platform,
--         country_name,
--         app_version AS first_app_version,
--         major_app_version AS first_major_app_version
--     FROM der.users
--     LEFT JOIN user_metrics.user_first_session_attributes
--             USING (analytics_id)
--     WHERE
--         account_created_at >= '2023-04-01'
-- ),
--     agg_sessions AS (
--         SELECT
--             new_users.analytics_id,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) = 0 THEN session_id
--                   END) AS count_d0_sessions,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 0 AND 7
--                           THEN session_id
--                   END) AS count_d7_sessions,
--             COUNT(DISTINCT CASE
--                               WHEN DATEDIFF('day', new_users.account_created_at,
--                                              sessions.session_start) BETWEEN 0 AND 7 THEN session_start::DATE
--                           END) AS count_d7_active_days,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) = 0
--                         THEN session_length_sec
--                     ELSE 0
--                 END) AS sum_d0_session_length,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 0 AND 7
--                         THEN session_length_sec
--                     ELSE 0
--                 END) AS sum_d7_session_length,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) = 0
--                         THEN count_open_calendar
--                     ELSE 0
--                 END) AS count_d0_open_calendar,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 0 AND 7
--                         THEN count_open_calendar
--                     ELSE 0
--                 END) AS count_d7_open_calendar,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) = 0
--                         THEN count_open_analysis
--                     ELSE 0
--                 END) AS count_d0_open_analysis,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 0 AND 7
--                         THEN count_open_analysis
--                     ELSE 0
--                 END) AS count_d7_open_analysis,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) = 0
--                         THEN count_open_content_tab
--                     ELSE 0
--                 END) AS count_d0_open_content_tab,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 0 AND 7
--                         THEN count_open_content_tab
--                     ELSE 0
--                 END) AS count_d7_open_content_tab,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) = 0
--                         THEN count_view_subscription_plans
--                     ELSE 0
--                 END) AS count_d0_view_subscription_plans,
--             SUM(CASE
--                     WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 0 AND 7
--                         THEN count_view_subscription_plans
--                     ELSE 0
--                 END) AS count_d7_view_subscription_plans,
--                 SUM(CASE
--                         WHEN DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 30 AND 60
--                             THEN count_track_period
--                         ELSE 0
--                     END) > 0 AS did_track_second_period
--         FROM new_users
--         LEFT JOIN der.sessions
--                 ON new_users.analytics_id = sessions.analytics_id AND
--                   DATEDIFF('day', new_users.account_created_at, sessions.session_start) BETWEEN 0 AND 60
--         GROUP BY 1
--     ),
--     agg_tracking AS (
--         SELECT
--             new_users.analytics_id,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at, combined_tracking.backend_updated_at) = 0
--                           THEN date
--                   END) AS count_d0_tracking_points,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at,
--                                     combined_tracking.backend_updated_at) BETWEEN 0 AND 7 THEN date
--                   END) AS count_d7_tracking_points,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at, combined_tracking.backend_updated_at) = 0 AND
--                           category != 'period' THEN date
--                   END) AS count_d0_nonperiod_tracking_points,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at,
--                                     combined_tracking.backend_updated_at) BETWEEN 0 AND 7 AND category != 'period'
--                           THEN date
--                   END) AS count_d7_nonperiod_tracking_points,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at, combined_tracking.backend_updated_at) = 0 AND
--                           category ILIKE '%birth%' THEN date
--                   END) AS count_d0_birth_control_tracking_points,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at,
--                                     combined_tracking.backend_updated_at) BETWEEN 0 AND 7 AND category ILIKE '%birth%'
--                           THEN date
--                   END) AS count_d7_birth_control_tracking_points,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at, combined_tracking.backend_updated_at) = 0 AND
--                           category IN ('tag', 'tags') THEN date
--                   END) AS count_d0_tags,
--             COUNT(CASE
--                       WHEN DATEDIFF('day', new_users.account_created_at,
--                                     combined_tracking.backend_updated_at) BETWEEN 0 AND 7 AND
--                           category IN ('tag', 'tags') THEN date
--                   END) AS count_d7_tags,
--             COUNT(DISTINCT CASE
--                               WHEN DATEDIFF('day', new_users.account_created_at,
--                                              combined_tracking.backend_updated_at) = 0 THEN category
--                           END) AS count_d0_tracking_categories,
--             COUNT(DISTINCT CASE
--                               WHEN DATEDIFF('day', new_users.account_created_at,
--                                              combined_tracking.backend_updated_at) BETWEEN 0 AND 7 THEN category
--                           END) AS count_d7_tracking_categories,
--             COUNT(DISTINCT CASE
--                               WHEN DATEDIFF('day', new_users.account_created_at,
--                                              combined_tracking.backend_updated_at) = 0 THEN type
--                           END) AS count_d0_tracking_options,
--             COUNT(DISTINCT CASE
--                               WHEN DATEDIFF('day', new_users.account_created_at,
--                                              combined_tracking.backend_updated_at) BETWEEN 0 AND 7 THEN type
--                           END) AS count_d7_tracking_options,
--             MAX(DISTINCT CASE
--                              WHEN DATEDIFF('day', new_users.account_created_at, combined_tracking.backend_updated_at) =
--                                   0 THEN DATEDIFF('day', date, combined_tracking.backend_updated_at)
--                          END) AS max_d0_tracking_into_past,
--             MAX(DISTINCT CASE
--                              WHEN DATEDIFF('day', new_users.account_created_at,
--                                           combined_tracking.backend_updated_at) BETWEEN 0 AND 7
--                                  THEN DATEDIFF('day', date, combined_tracking.backend_updated_at)
--                          END) AS max_d7_tracking_into_past
--         FROM new_users
--         LEFT JOIN (
-- --             SELECT
-- --                 analytics_id,
-- --                 date,
-- --                 category,
-- --                 type,
-- --                 backend_updated_at
-- --             FROM der.tracking
-- --             UNION ALL
--             SELECT
--                 analytics_id,
--                 date,
--                 category,
--                 type,
--                 backend_updated_at
--             FROM der.backend_tracking
--             WHERE
--                 revision_type = 'measurements_tracked'
--         ) AS combined_tracking
--                 ON new_users.analytics_id = combined_tracking.analytics_id AND
--                   DATEDIFF('day', new_users.account_created_at, combined_tracking.backend_updated_at) BETWEEN 0 AND 7
--         GROUP BY 1
--     ),
--     agg_events AS (
--         SELECT
--             new_users.analytics_id,
--             COUNT(CASE
--                       WHEN mobile_event_name = 'Show Error Screen' AND
--                           DATEDIFF('day', new_users.account_created_at, events.derived_tstamp) = 0 THEN root_id
--                   END) AS count_d0_show_error_screen,
--             COUNT(CASE
--                       WHEN mobile_event_name = 'Show Error Screen' AND
--                           DATEDIFF('day', new_users.account_created_at, events.derived_tstamp) BETWEEN 0 AND 7
--                           THEN root_id
--                   END) AS count_d7_show_error_screen,
--             COUNT(CASE
--                       WHEN mobile_event_name = 'Open Multi Day Tracker' AND
--                           DATEDIFF('day', new_users.account_created_at, events.derived_tstamp) = 0 THEN root_id
--                   END) AS count_d0_open_multi_day_tracker,
--             COUNT(CASE
--                       WHEN mobile_event_name = 'Open Multi Day Tracker' AND
--                           DATEDIFF('day', new_users.account_created_at, events.derived_tstamp) BETWEEN 0 AND 7
--                           THEN root_id
--                   END) AS count_d7_open_multi_day_tracker,
--             COUNT(CASE
--                       WHEN mobile_event_name = 'Open Mode Picker' AND
--                           DATEDIFF('day', new_users.account_created_at, events.derived_tstamp) = 0 THEN root_id
--                   END) AS count_d0_open_mode_picker,
--             COUNT(CASE
--                       WHEN mobile_event_name = 'Open Mode Picker' AND
--                           DATEDIFF('day', new_users.account_created_at, events.derived_tstamp) BETWEEN 0 AND 7
--                           THEN root_id
--                   END) AS count_d7_open_mode_picker
--         FROM new_users
--         LEFT JOIN der.events
--                 ON new_users.analytics_id = events.analytics_id AND
--                   DATEDIFF('day', new_users.account_created_at, events.derived_tstamp) BETWEEN 0 AND 7
--         GROUP BY 1
--     ),
--     agg_reminders AS (
--         SELECT
--             new_users.analytics_id,
--             COUNT(DISTINCT CASE
--                               WHEN enabled AND
--                                     DATEDIFF('day', new_users.account_created_at, backend_reminder_events.created_at) =
--                                     0 THEN reminder_type
--                           END) AS count_d0_reminders_enabled,
--             COUNT(DISTINCT CASE
--                               WHEN enabled AND DATEDIFF('day', new_users.account_created_at,
--                                                          backend_reminder_events.created_at) BETWEEN 0 AND 7
--                                   THEN reminder_type
--                           END) AS count_d7_reminders_enabled
--         FROM new_users
--         LEFT JOIN der.backend_reminder_events
--                 ON new_users.analytics_id = backend_reminder_events.analytics_id AND
--                   DATEDIFF('day', new_users.account_created_at, backend_reminder_events.created_at) BETWEEN 0 AND 7
--         GROUP BY 1
--     )
-- SELECT
--     analytics_id,
--     account_created_at,
--     platform,
--     country_name,
--     first_app_version,
--     first_major_app_version,
--     count_d0_sessions,
--     count_d7_sessions,
--     count_d7_active_days,
--     sum_d0_session_length,
--     sum_d7_session_length,
--     count_d0_open_calendar,
--     count_d7_open_calendar,
--     count_d0_open_analysis,
--     count_d7_open_analysis,
--     count_d0_open_content_tab,
--     count_d7_open_content_tab,
--     count_d0_view_subscription_plans,
--     count_d7_view_subscription_plans,
--     did_track_second_period,
--     count_d0_show_error_screen,
--     count_d7_show_error_screen,
--     count_d0_open_multi_day_tracker,
--     count_d7_open_multi_day_tracker,
--     count_d0_open_mode_picker,
--     count_d7_open_mode_picker,
--     count_d0_tracking_points,
--     count_d7_tracking_points,
--     count_d0_nonperiod_tracking_points,
--     count_d7_nonperiod_tracking_points,
--     count_d0_birth_control_tracking_points,
--     count_d7_birth_control_tracking_points,
--     count_d0_tags,
--     count_d7_tags,
--     count_d0_tracking_categories,
--     count_d7_tracking_categories,
--     count_d0_tracking_options,
--     count_d7_tracking_options,
--     max_d0_tracking_into_past,
--     max_d7_tracking_into_past,
--     count_d0_reminders_enabled,
--     count_d7_reminders_enabled
-- FROM new_users
-- INNER JOIN agg_sessions
--         USING (analytics_id)
-- INNER JOIN agg_events
--         USING (analytics_id)
-- INNER JOIN agg_trackingt
--         USING (analytics_id)
-- INNER JOIN agg_reminders
--         USING (analytics_id)
-- )
-- ;

SELECT *
FROM temp.new_user_activation_metrics_v1
LIMIT 500
;
