-- create table temp.cycle_prediction_sample (
--     analytics_id string,
--     cycle_count int,
--     total_data_points_tracked int,
--     average_data_points_tracked_per_cycle double,
--     total_dates_tracked int,
--     average_dates_tracked_per_cycle double,
--     total_days int,
--     cycles_with_cramps int,
--     total_cramps_tracked int,
--     average_cramps_tracked_per_cycle double,
--     tracked_cramps_cycle_1 int,
--     tracked_cramps_cycle_2 int,
--     tracked_cramps_cycle_3 int,
--     tracked_cramps_cycle_4 int,
--     tracked_cramps_cycle_5 int,
--     tracked_cramps_cycle_6 int,
--     tracked_cramps_latest_cycle int
-- )
--     LOCATION 's3://clue-data-prod-athena-iceberg-storage/iceberg/temp/cycle_prediction_sample'
--     TBLPROPERTIES (
--     'table_type'='iceberg'
-- );


-- insert into temp.cycle_prediction_sample (
--     analytics_id,
--     cycle_count,
--     total_data_points_tracked,
--     average_data_points_tracked_per_cycle,
--     total_dates_tracked,
--     average_dates_tracked_per_cycle,
--     total_days,
--     cycles_with_cramps,
--     total_cramps_tracked,
--     average_cramps_tracked_per_cycle,
--     tracked_cramps_cycle_1,
--     tracked_cramps_cycle_2,
--     tracked_cramps_cycle_3,
--     tracked_cramps_cycle_4,
--     tracked_cramps_cycle_5,
--     tracked_cramps_cycle_6,
--     tracked_cramps_latest_cycle
-- )
-- with counts_by_user as (
--     select analytics_id, count(1) as cycles, max(cycle_id) as latest_cycle
--     from der.backend_cycles
--     where cycle_excluded = false and cycle_predicted = false and current_cycle = false
--     group by 1
--     having count(1) > 2
-- ),

-- sample as (
--     select backend_cycles.*, counts_by_user.cycles, counts_by_user.latest_cycle
--     from der.backend_cycles
--     join counts_by_user on (backend_cycles.analytics_id = counts_by_user.analytics_id)
--     where cycle_excluded = false and cycle_predicted = false and current_cycle = false
--       and cycle_id >= latest_cycle - 6 and cycle_id <= latest_cycle
-- ),

-- cycles_with_tracking_data as (
--     select 
--         s.analytics_id, s.cycle_start, s.cycle_end, s.cycle_id, s.latest_cycle, s.cycles,
--         count(t.measurement_id) as data_points_tracked,
--         count(distinct t.date) as dates_tracked,
--         count(distinct case when t.type = 'period_cramps' then t.date else null end) as cramps_tracked
--     from sample s
--     left join der.backend_tracking t
--      on (s.analytics_id = t.analytics_id and t.date between s.cycle_start and s.cycle_end)
--     group by s.analytics_id, s.cycle_start, s.cycle_end, s.cycle_id, s.latest_cycle, s.cycles
-- )

-- select
--     analytics_id,
--     count(cycle_id) as cycle_count,
--     sum(data_points_tracked) as total_data_points_tracked,
--     avg(data_points_tracked) as average_data_points_tracked_per_cycle,
--     sum(dates_tracked) as total_dates_tracked,
--     avg(dates_tracked) as average_dates_tracked_per_cycle,
--     date_diff('day', min(cycle_start), max(cycle_end)) as total_days,
--     count(case when cramps_tracked > 0 then 1 else null end) as cycles_with_cramps,
--     sum(cramps_tracked) as total_cramps_tracked,
--     avg(cramps_tracked) as average_cramps_tracked_per_cycle,
--     max(case when cycle_id = latest_cycle - 6 and cramps_tracked >= 1 then cramps_tracked else 0 end) as tracked_cramps_cycle_1,
--     max(case when cycle_id = latest_cycle - 5 and cramps_tracked >= 1 then cramps_tracked else 0 end) as tracked_cramps_cycle_2,
--     max(case when cycle_id = latest_cycle - 4 and cramps_tracked >= 1 then cramps_tracked else 0 end) as tracked_cramps_cycle_3,
--     max(case when cycle_id = latest_cycle - 3 and cramps_tracked >= 1 then cramps_tracked else 0 end) as tracked_cramps_cycle_4,
--     max(case when cycle_id = latest_cycle - 2 and cramps_tracked >= 1 then cramps_tracked else 0 end) as tracked_cramps_cycle_5,
--     max(case when cycle_id = latest_cycle - 1 and cramps_tracked >= 1 then cramps_tracked else 0 end) as tracked_cramps_cycle_6,
--     max(case when cycle_id = latest_cycle and cramps_tracked >= 1 then cramps_tracked else 0 end) as tracked_cramps_latest_cycle
-- from cycles_with_tracking_data
-- group by 1
-- ;
